import {ColorShceme} from './type';

const dark: ColorShceme = {
  primary: '#000000',
  secondary: '#FFFFFF',
  active: '#33FFFF',
  passive: '#006666',
  pageBackground: '#000000',
  statusbar: '#000000',
  textInputBackground: '#000000',
  textInputBorder: '#000000',
  textInputFocused: '#33FFFF',
  text: '#FFFFFF',
  buttonFilledBackground: '#33FFFF',
  buttonOutlinedBackground: '#000000',
  buttonSimpliedBackground: 'transparent',
  buttonFilledText: '#000000',
  buttonOutlinedText: '#33FFFF',
  buttonSimpliedText: '#33FFFF',
  buttonFilledPressedText: '#000000',
  buttonOutlinedPressedText: '#CC0000',
  buttonSimpliedPressedText: '#CC0000',
  buttonFilledPressedBackgorund: '#CC0000',
  buttonOuıtlinedPressedBackgorund: '#CC0000',
  buttonSimpliedPressedBackground: 'transparent',
  buttonFilledBorder: '#33FFFF',
  buttonOutlinedBorder: '#33FFFF',
  buttonSimpliedBorder: 'transparent',
  buttonFilledPressedBorder: '#CC0000',
  buttonOutlinedPressedBorder: '#CC0000',
  buttonSimpliedPressedBorder: 'transparent',
  radioButtonActive: '#33FFFF',
  radioButtonPassive: '#006666',
  checkBoxActive: '#33FFFF',
  checkBoxPassive: '#006666',
  chipActive: '#33FFFF',
  chipPassive: '#006666',
};

export default dark;
