import {ColorShceme} from './type';

const light: ColorShceme = {
  primary: '#FFFFFF',
  secondary: '#000000',
  active: '#CC0000',
  passive: '#FF9999',
  pageBackground: '#FFFFFF',
  statusbar: '#FFFFFF',
  textInputBackground: '#FFFFFF',
  textInputBorder: '#FFFFFF',
  textInputFocused: '#CC0000',
  text: '#000000',
  buttonFilledBackground: '#CC0000',
  buttonOutlinedBackground: '#FFFFFF',
  buttonSimpliedBackground: 'transparent',
  buttonFilledText: '#FFFFFF',
  buttonOutlinedText: '#CC0000',
  buttonSimpliedText: '#CC0000',
  buttonFilledPressedText: '#000000',
  buttonOutlinedPressedText: '#33FFFF',
  buttonSimpliedPressedText: '#33FFFF',
  buttonFilledPressedBackgorund: '#33FFFF',
  buttonOuıtlinedPressedBackgorund: '#33FFFF',
  buttonSimpliedPressedBackground: 'transparent',
  buttonFilledBorder: '#CC0000',
  buttonOutlinedBorder: '#CC0000',
  buttonSimpliedBorder: 'transparent',
  buttonFilledPressedBorder: '#33FFFF',
  buttonOutlinedPressedBorder: '#33FFFF',
  buttonSimpliedPressedBorder: 'transparent',
  radioButtonActive: '#CC0000',
  radioButtonPassive: '#FF9999',
  checkBoxActive: '#CC0000',
  checkBoxPassive: '#FF9999',
  chipActive: '#CC0000',
  chipPassive: '#FF9999',
};

export default light;
