const COMPONENT_LIST = [
    "Badge",
    "Button",
    "BottomSheet",
    "Card",
    "Chat",
    "CheckBox - input",
    "CheckBoxGroup - input",
    "Chip - input",
    "ChipGroup - input",
    "Divider",
    "DateTimePicker",
    "Modal",
    "PageContainer",
    "PickerBox - input",
    "RadioButton - input",
    "RadioButtonGroup - input",
    "SegmentedButton - input",
    "SelectBox - input",
    "Separator",
    "Skeleton",
    "SnackBar",
    "TapSelector",
    "Text",
    "TextInput - input",
    "WheelPicker",
]

export default COMPONENT_LIST