const MAIN = "MAIN"
const BADGE = "BADGE"
const BUTTON = "BUTTON"
const BOTTOMSHEET = "BOTTOMSHEET"
const CARD = "CARD"
const CHAT = "CHAT"
const CHECKBOX = "CHECKBOX"
const CHECKBOXGROUP = "CHECKBOXGROUP"
const CHIP = "CHIP"
const CHIPGROUP = "CHIPGROUP"
const DATETIMEPICKER = "DATETIMEPICKER"
const DIVIDER = "DIVIDER"
const MODAL = "MODAL"
const PAGECONTAINER = "PAGECONTAINER"
const PICKERBOX = "PICKERBOX"
const RADIOBUTTON = "RADIOBUTTON"
const RADIOBUTTONGROUP = "RADIOBUTTONGROUP"
const SEGMENTEDBUTTON = "SEGMENTEDBUTTON"
const SELECTBOX = "SELECTBOX"
const SEPARATOR = "SEPARATOR"
const SNACKBAR = "SNACKBAR"
const TAPSELECTOR = "TAPSELECTOR"
const TEXT = "TEXT"
const TEXTINPUT = "TEXTINPUT"
const WHEELPICKER = "WHEELPICKER"

const PAGE_NAMES = {
    MAIN,
    BADGE,
    BUTTON,
    BOTTOMSHEET,
    CARD,
    CHAT,
    CHECKBOX,
    CHECKBOXGROUP,
    CHIP,
    CHIPGROUP,
    DATETIMEPICKER,
    DIVIDER,
    MODAL,
    PAGECONTAINER,
    PICKERBOX,
    RADIOBUTTON,
    RADIOBUTTONGROUP,
    SEGMENTEDBUTTON,
    SELECTBOX,
    SEPARATOR,
    SNACKBAR,
    TAPSELECTOR,
    TEXT,
    TEXTINPUT,
    WHEELPICKER,
}

export default PAGE_NAMES