const MAIN = "MAIN"
const BADGE = "BADGE"
const BUTTON = "BUTTON"
const BOTTOM_SHEET = "BOTTOM_SHEET"
const CARD = "CARD"
const CHAT = "CHAT"
const CHECK_BOX = "CHECK_BOX"
const CHECK_BOX_GROUP = "CHECK_BOX_GROUP"
const CHIP = "CHIP"
const CHIP_GROUP = "CHIP_GROUP"
const DATE_TIME_PICKER = "DATE_TIME_PICKER"
const DIVIDER = "DIVIDER"
const MODAL = "MODAL"
const PAGE_CONTAINER = "PAGE_CONTAINER"
const PICKER_BOX = "PICKER_BOX"
const RADIO_BUTTON = "RADIO_BUTTON"
const RADIO_BUTTON_GROUP = "RADIO_BUTTON_GROUP"
const SEGMENTED_BUTTON = "SEGMENTED_BUTTON"
const SELECT_BOX = "SELECT_BOX"
const SEPARATOR = "SEPARATOR"
const SKELETON = "SKELETON"
const SNACK_BAR = "SNACK_BAR"
const TAP_SELECTOR = "TAP_SELECTOR"
const TEXT = "TEXT"
const TEXT_INPUT = "TEXT_INPUT"
const WHEEL_PICKER = "WHEEL_PICKER"

const PAGE_NAMES = {
    MAIN,
    BADGE,
    BUTTON,
    BOTTOM_SHEET,
    CARD,
    CHAT,
    CHECK_BOX,
    CHECK_BOX_GROUP,
    CHIP,
    CHIP_GROUP,
    DATE_TIME_PICKER,
    DIVIDER,
    MODAL,
    PAGE_CONTAINER,
    PICKER_BOX,
    RADIO_BUTTON,
    RADIO_BUTTON_GROUP,
    SEGMENTED_BUTTON,
    SELECT_BOX,
    SEPARATOR,
    SKELETON,
    SNACK_BAR,
    TAP_SELECTOR,
    TEXT,
    TEXT_INPUT,
    WHEEL_PICKER,
}

export default PAGE_NAMES